/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ActionAfterSubmission } from "./actionaftersubmission";
import { FormElementDto } from "./formelementdto";
import { Expose, Transform, Type } from "class-transformer";

/**
 * Successful Response
 */
export class ApiFormDto extends SpeakeasyBase {
  /**
   * Action after the submission
   */
  @SpeakeasyMetadata()
  @Expose({ name: "actionAfterSubmission" })
  @Type(() => ActionAfterSubmission)
  actionAfterSubmission?: ActionAfterSubmission;

  /**
   * Time when form was created
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt?: Date;

  /**
   * List of form fields
   */
  @SpeakeasyMetadata({ elemType: FormElementDto })
  @Expose({ name: "elements" })
  @Type(() => FormElementDto)
  elements: FormElementDto[];

  /**
   * Form identifier
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;

  /**
   * Form name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * Can resubmit multiple times
   */
  @SpeakeasyMetadata()
  @Expose({ name: "resubmitEnabled" })
  resubmitEnabled: boolean;

  /**
   * Time when form was update last time
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updatedAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt?: Date;
}
