/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApiRequestErrorDetails } from "./apirequesterrordetails";
import { Expose, Type } from "class-transformer";

export class ApiRequestError extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "serviceException" })
  @Type(() => ApiRequestErrorDetails)
  serviceException?: ApiRequestErrorDetails;
}
