/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiRequestErrorDetails } from "./eightytwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93apirequesterrordetails";
import { Expose, Type } from "class-transformer";

export class EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiRequestError extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "serviceException" })
  @Type(
    () =>
      EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiRequestErrorDetails
  )
  serviceException?: EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiRequestErrorDetails;
}
