/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ActionAfterSubmission } from "./eightytwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93actionaftersubmission";
import { EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93FormElementDto } from "./eightytwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93formelementdto";
import { Expose, Transform, Type } from "class-transformer";

/**
 * Successful Response
 */
export class EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiFormDto extends SpeakeasyBase {
  /**
   * Action after the submission
   */
  @SpeakeasyMetadata()
  @Expose({ name: "actionAfterSubmission" })
  @Type(
    () =>
      EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ActionAfterSubmission
  )
  actionAfterSubmission?: EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ActionAfterSubmission;

  /**
   * Time when form was created
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt?: Date;

  /**
   * List of form fields
   */
  @SpeakeasyMetadata({
    elemType:
      EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93FormElementDto,
  })
  @Expose({ name: "elements" })
  @Type(
    () =>
      EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93FormElementDto
  )
  elements: EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93FormElementDto[];

  /**
   * Form identifier
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;

  /**
   * Form name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * Can resubmit multiple times
   */
  @SpeakeasyMetadata()
  @Expose({ name: "resubmitEnabled" })
  resubmitEnabled: boolean;

  /**
   * Time when form was update last time
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updatedAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt?: Date;
}
