/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiRequestErrorDetails extends SpeakeasyBase {
  /**
   * Identifier of the error.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "messageId" })
  messageId?: string;

  /**
   * Detailed error description.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "text" })
  text?: string;

  /**
   * Map of validation errors.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "validationErrors" })
  validationErrors?: Record<string, string[]>;
}
