/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiRequestError } from "./eightytwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93apirequesterror";
import { Expose, Type } from "class-transformer";

/**
 * Bad Request
 */
export class EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiException extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "requestError" })
  @Type(
    () =>
      EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiRequestError
  )
  requestError?: EightyTwoacced121042a63992bde26d4dd141353f7b2633c33f797139d71d4bef2a93ApiRequestError;
}
