/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { IamPersonV2 } from "./iampersonv2";
import { Expose, Type } from "class-transformer";

/**
 * Contains the data used for person creation (if it does not exist) or partial update (if it exists)
 */
export class FlowPersonRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "flowVariables" })
  flowVariables?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  @Expose({ name: "personData" })
  @Type(() => IamPersonV2)
  personData: IamPersonV2;
}
