/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { IamSalesforceV2 } from "./iamsalesforcev2";
import { Expose, Type } from "class-transformer";

export class IamIntegrationsV2 extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "salesforce" })
  @Type(() => IamSalesforceV2)
  salesforce?: IamSalesforceV2;
}
