/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class IamLiveChatContactSystemData extends SpeakeasyBase {}

export class IamLiveChatContact extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "applicationId" })
    applicationId?: string;

    @SpeakeasyMetadata({ elemType: IamLiveChatContactSystemData })
    @Expose({ name: "systemData" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, IamLiveChatContactSystemData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], IamLiveChatContactSystemData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    systemData?: Record<string, IamLiveChatContactSystemData>;

    @SpeakeasyMetadata()
    @Expose({ name: "userId" })
    userId?: string;
}
