/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class IamLineContactSystemData extends SpeakeasyBase {}

export class IamLineContact extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "applicationId" })
    applicationId?: string;

    @SpeakeasyMetadata({ elemType: IamLineContactSystemData })
    @Expose({ name: "systemData" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, IamLineContactSystemData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], IamLineContactSystemData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    systemData?: Record<string, IamLineContactSystemData>;

    @SpeakeasyMetadata()
    @Expose({ name: "userId" })
    userId?: string;
}
