/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamSalesforceV2 extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "contactId" })
  contactId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "leadId" })
  leadId?: string;
}
