/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2 } from "./ninehundredtrillionsixhundredandthirtyfourbillionthreehundredandthirtyninemillionfivehundredandtwelvethousandandfortyonedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0iampersonv2";
import { Expose, Type } from "class-transformer";

/**
 * Contains the data used for person creation (if it does not exist) or partial update (if it exists)
 */
export class NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0FlowPersonRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "flowVariables" })
  flowVariables?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  @Expose({ name: "personData" })
  @Type(
    () =>
      NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2
  )
  personData: NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2;
}
