/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamSalesforceV2 } from "./ninehundredtrillionsixhundredandthirtyfourbillionthreehundredandthirtyninemillionfivehundredandtwelvethousandandfortyonedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0iamsalesforcev2";
import { Expose, Type } from "class-transformer";

export class NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamIntegrationsV2 extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "salesforce" })
  @Type(
    () =>
      NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamSalesforceV2
  )
  salesforce?: NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamSalesforceV2;
}
