/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamContactV2 } from "./ninehundredtrillionsixhundredandthirtyfourbillionthreehundredandthirtyninemillionfivehundredandtwelvethousandandfortyonedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0iamcontactv2";
import { NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamIntegrationsV2 } from "./ninehundredtrillionsixhundredandthirtyfourbillionthreehundredandthirtyninemillionfivehundredandtwelvethousandandfortyonedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0iamintegrationsv2";
import { Expose, Type } from "class-transformer";

export enum NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2GenderEnum {
  Male = "MALE",
  Female = "FEMALE",
}

export enum NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2ModifiedFromEnum {
  Api = "API",
  Portal = "PORTAL",
  WebSDK = "WEB_SDK",
  Integration = "INTEGRATION",
  Push = "PUSH",
  Facebook = "FACEBOOK",
  Line = "LINE",
  Telegram = "TELEGRAM",
  Salesforce = "SALESFORCE",
  Dynamics = "DYNAMICS",
  Zapier = "ZAPIER",
  Forms = "FORMS",
  Ams = "AMS",
  Computed = "COMPUTED",
  Answers = "ANSWERS",
  Conversations = "CONVERSATIONS",
}

export enum NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2OriginEnum {
  Api = "API",
  Portal = "PORTAL",
  WebSDK = "WEB_SDK",
  Integration = "INTEGRATION",
  Push = "PUSH",
  Facebook = "FACEBOOK",
  Line = "LINE",
  Telegram = "TELEGRAM",
  Salesforce = "SALESFORCE",
  Dynamics = "DYNAMICS",
  Zapier = "ZAPIER",
  Forms = "FORMS",
  Ams = "AMS",
  Computed = "COMPUTED",
  Answers = "ANSWERS",
  Conversations = "CONVERSATIONS",
}

export enum NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2TypeEnum {
  Customer = "CUSTOMER",
  Lead = "LEAD",
  Agent = "AGENT",
}

export class NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2 extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "address" })
  address?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "birthDate" })
  birthDate?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "city" })
  city?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "companyId" })
  companyId?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "computedAttributes" })
  computedAttributes?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  @Expose({ name: "contactInformation" })
  @Type(
    () =>
      NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamContactV2
  )
  contactInformation: NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamContactV2;

  @SpeakeasyMetadata()
  @Expose({ name: "country" })
  country?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "createdAt" })
  createdAt?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "customAttributes" })
  customAttributes?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  @Expose({ name: "externalId" })
  externalId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "firstName" })
  firstName?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "gender" })
  gender?: NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2GenderEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "integrations" })
  @Type(
    () =>
      NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamIntegrationsV2
  )
  integrations?: NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamIntegrationsV2;

  @SpeakeasyMetadata()
  @Expose({ name: "lastName" })
  lastName?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "middleName" })
  middleName?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "modifiedAt" })
  modifiedAt?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "modifiedFrom" })
  modifiedFrom?: NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2ModifiedFromEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "origin" })
  origin?: NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2OriginEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "profilePicture" })
  profilePicture?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "tags" })
  tags?: string[];

  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: NineHundredTrillionSixHundredAndThirtyFourBillionThreeHundredAndThirtyNineMillionFiveHundredAndTwelveThousandAndFortyOnedd9c6cd5c4ad62d6cf43ea57e0548f5deeceb9f79d92b92f0IamPersonV2TypeEnum;
}
