/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetFormSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=apiKey;subtype=header;name=Authorization",
  })
  apiKeyHeader: string;
}

export class GetFormRequest extends SpeakeasyBase {
  /**
   * ID of a form
   */
  @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
  id: string;
}

export class GetFormResponse extends SpeakeasyBase {
  /**
   * Unauthorized
   */
  @SpeakeasyMetadata()
  apiException?: shared.ApiException;

  /**
   * Successful Response
   */
  @SpeakeasyMetadata()
  apiFormDto?: shared.ApiFormDto;

  @SpeakeasyMetadata()
  body?: Uint8Array;

  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
